apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: ${namespace}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: eah0592@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudDNS:
            project: ${project}
