apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: ${namespace}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: eah0592@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudDNS:
            project: ${project}
